---
- hosts: all
  tasks:

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: dist

    - name: Install nginx web server
      become: yes
      apt: name=nginx state=latest update_cache=true

    # figure out ow to set Exoscale security group settings
    # Instance must be reachable on port 80

    - name: clone git repo
      become: yes
      git:
        repo: 'https://github.com/Bouni/swisshydroapi.git'
        dest: /tmp/swisshydroapi
        force: yes

    - name: Ensures /srv/swisshydroapi dir exists
      become: yes
      file: 
        path: /srv/swisshydroapi 
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy app.py to /srv/swisshydroapi/
      become: yes
      copy:
        src: /tmp/swisshydroapi/app.py 
        dest: /srv/swisshydroapi/app.py
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Ensures /srv/swisshydroapi/docs dir exists
      become: yes
      file: 
        path: /srv/swisshydroapi/docs 
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Copy docs to /srv/swisshydroapi/
      become: yes
      copy:
        src: /tmp/swisshydroapi/docs/docs.html 
        dest: /srv/swisshydroapi/docs/docs.html
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Copy service file to /etc/systemd/system
      become: yes
      copy:
        src: /tmp/swisshydroapi/swisshydroapi.service
        dest: /etc/systemd/system/swisshydroapi.service
        remote_src: yes
    
    - name: Install pip
      become: yes
      apt: name=python3-pip state=latest update_cache=true

    - name: Install virtualenv
      become: yes
      pip:
        executable: pip3 
        name: virtualenv
        state: present

    - name: Install python requirements
      become: yes
      pip:
        virtualenv_python: python3
        requirements: /tmp/swisshydroapi/requirements.txt 
        virtualenv: /srv/swisshydroapi/venv
    
    - name: Copy nginx config file to /etc/nginx/sites-available
      become: yes
      copy:
        src: /tmp/swisshydroapi/swisshydroapi.bouni.de
        dest: /etc/nginx/sites-available/swisshydroapi.bouni.de
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create a symbolic link
      file:
        src: /etc/nginx/sites-available/swisshydroapi.bouni.de
        dest: /etc/nginx/sites-enabled/swisshydroapi.bouni.de
        owner: www-data
        group: www-data
        state: link

    - name: Replace username with prompted value
      become: yes
      lineinfile: 
        path: /tmp/swisshydroapi/bafu.service
        regexp: 'ExecStart'
        line: 'ExecStart=curl -o /src/swisshydroapi/hydroweb.xml --anyauth --user "{{ bafuuser }}":"{{ bafupass }}" https://www.hydrodata.ch/data/plc/xml/hydroweb.xml'

    - name: Copy BAFU download timer to /etc/systemd/system
      become: yes
      copy:
        src: /tmp/swisshydroapi/bafu.timer
        dest: /etc/systemd/system/bafu.timer
        remote_src: yes
    
    - name: Copy BAFU download service file to /etc/systemd/system
      become: yes
      copy:
        src: /tmp/swisshydroapi/bafu.service
        dest: /etc/systemd/system/bafu.service
        remote_src: yes

    - name: Enable and start swisshydroapi.service
      become: yes
      systemd:
        name: swisshydroapi.service
        state: started
        enabled: yes
        masked: no
        daemon_reload: yes
    
    - name: Enable and start bafu.timer
      become: yes
      systemd:
        name: bafu.timer
        state: started
        enabled: yes
        masked: no
        daemon_reload: yes

  vars_prompt:
    
    - name: "bafuuser"
      prompt: "Enter BAFU username"
    
    - name: "bafupass"
      prompt: "Enter BAFU password"
